---
AWSTemplateFormatVersion: '2010-09-09'
Description: This template creates a IAM role that can create Systems Manager sessions.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Configuration
      Parameters:
      - PrivateSubnet
      - AssumeRoleARN
      - InstanceName
    ParameterLabels:
      PrivateSubnet:
        default: Location of target instances
      AssumeRoleARN:
        default: ARN which can assume the role
      InstanceName:
        default: Name of the instance that role will have access to
Parameters:
  PrivateSubnet:
    Type: String
    AllowedValues:
    - 'true'
    - 'false'
    Default: 'false'
    Description: Location of target instances
  AssumeRoleARN:
    Type: String
    Description: ARN which can assume the role
  InstanceName:
    Type: String
    Description: Name of the instance that role will have access to
Resources:
  Role:
    Type: AWS::IAM::Role
    Properties: 
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              AWS: !Ref AssumeRoleARN
            Action: 
              - "sts:AssumeRole"
            Condition:
              Bool:
                "aws:MultiFactorAuthPresent": "true"
      Path: !Sub "/${AWS::StackName}/"
      Policies: 
        - PolicyName: FullAdminAccessToSessions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Action:
              - ssm:TerminateSession
              - ssm:ResumeSession
              - ssm:DescribeSessions
              - ssm:GetConnectionStatus
              - ssm:DescribeInstanceInformation
              - ec2:DescribeInstances
              Effect: Allow
              Resource:
              - "*"
        - PolicyName: StartSpecificSessions
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Action:
              - ssm:StartSession
              Effect: Allow
              Resource:
              - "*"
              Condition:
                StringLike:
                  "ssm:resourceTag/Name":
                    - Ref: InstanceName
Outputs:
  Role:
    Description: Access Role
    Value:
      Ref: Role
    Export:
      Name:
        Fn::Sub: "${AWS::StackName}-Role"
